--- 
- name: Set up podman machine on WSL2
  hosts: localhost
  tasks:
    - name: Update and upgrade
      become: true
      apt:
        upgrade: full
        update_cache: true

    - name: install packages
      become: true
      apt:
        name: 
          - neovim 
          - tmux
          - ranger

    - name: Set editor
      shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 100
      become: true

    - name: Set editor env var
      become: true
      copy:
        content: |
          export EDITOR="/usr/bin/nvim"
        dest: /etc/profile.d/editor.sh

    - name: ensure rifle.conf exists
      tags: rifle
      command:
        cmd: ranger --copy-config=rifle
        creates: "~/.config/ranger/rifle.conf"

    - name: open yml / yaml in nvim
      tags: ranger
      blockinfile:
        path: "~/.config/ranger/rifle.conf"
        insertbefore: BOF
        block: |

          # Prefer $EDITOR/$VISUAL for YAML and patch files.
          # Matches .yml, .yaml and .patch; placed before generic/xdg-open rules.
          ext ya?ml|patch, label editor = ${VISUAL:-$EDITOR} -- "$@"
          ext ya?ml|patch, label pager  = ${PAGER:-less} -- "$@"

    - name: Deploy init.lua for Neovim
      tags: neovim
      blockinfile:
        dest: "{{ lookup('env','HOME') }}/.config/nvim/init.lua"
        create: true
        marker: -- {mark} ANSIBLE MANAGED DOTFILE --
        content: |
          -- Press Shift+Tab to deindent
          vim.keymap.set("i", "<S-Tab>", "<C-d>")
          vim.keymap.set("n", "<S-Tab>", "<<")
          vim.keymap.set("v", "<S-Tab>", "<gv")

    - name: Cycle bash completion with TAB
      tags: tmux
      blockinfile:
        block: |
          set editing-mode vi

          set keymap vi-command
          "\C-l": clear-screen

          set keymap vi-insert
          "\C-l": clear-screen
          TAB: menu-complete
          "\e[Z": menu-complete-backward
          set show-all-if-ambiguous on
          set menu-complete-display-prefix on

          bind -Tcopy-mode-vi DoubleClick1Pane select-word
          bind -Tcopy-mode-vi TripleClick1Pane select-line
        dest: ~/.inputrc
        create: true

    - name: git set up
      shell: git config --global init.defaultBranch main
    - name: git alias
      git_config:
        scope: global
        name: alias.log-graph
        value: log --graph
    
    - name: Edit tmux settings
      tags: tmux
      blockinfile:
        block: |
          set -g mouse on
          # Open the current directory when splitting a window
          bind '"' split-window -v -c "#{pane_current_path}"
          bind % split-window -h -c "#{pane_current_path}"

          # Use vim bindings to navigate in windows
          bind h select-pane -L
          bind j select-pane -D
          bind k select-pane -U
          bind l select-pane -R

          # Display working directory
          set -g status-left "#{pane_current_path}"
          set -g status-left-length 85 # Longer status pane

          # Use vi mode for selection
          setw -g mode-keys vi
          # Update default binding of `Enter` to also use copy-pipe
          bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-no-clear
          bind-key -T copy-mode-vi v                 send      -X begin-selection
          bind-key -T copy-mode-vi y                 send      -X copy-selection-no-clear
          bind-key -T copy-mode-vi Enter             send      -X copy-selection-no-clear # To immediately exit: use copy-selection-and-cancel

        dest: ~/.tmux.conf
        create: true


