--- 
- name: Set up podman machine on WSL2
  hosts: localhost

  tasks:
    - name: Update and upgrade
      become: true
      apt:
        upgrade: full
        update_cache: true

    - name: install packages
      become: true
      apt:
        name: 
          - neovim 
          - tmux

    - name: Cycle bash completion with TAB
      blockinfile:
        block: |
          set editing-mode vi

          set keymap vi-command
          "\C-l": clear-screen

          set keymap vi-insert
          "\C-l": clear-screen
          TAB: menu-complete
          "\e[Z": menu-complete-backward
          set show-all-if-ambiguous on
          set menu-complete-display-prefix on
        dest: ~/.inputrc
        create: true

    - name: git set up
      shell: git config --global init.defaultBranch main
    - name: git alias
      git_config:
        scope: global
        name: alias.log-graph
        value: log --graph
    
    - name: Edit tmux settings
      blockinfile:
        block: |
          set -g mouse on
          # Open the current directory when splitting a window
          bind '"' split-window -v -c "#{pane_current_path}"
          bind % split-window -h -c "#{pane_current_path}"

          # Use vim bindings to navigate in windows
          bind h select-pane -L
          bind j select-pane -D
          bind k select-pane -U
          bind l select-pane -R
        dest: ~/.tmux.conf
        create: true
